# Generated by Django 5.0.14 on 2026-07-15 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign_updates', '0001_initial'),
        ('milestones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignupdate',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updates', to='milestones.milestone'),
        ),
        migrations.AddField(
            model_name='campaignupdate',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posted_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='campaignupdate',
            index=models.Index(fields=['campaign', 'created_at'], name='campaign_up_campaig_762ad1_idx'),
        ),
    ]
