# Generated by Django 5.0.14 on 2026-08-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('campaign_update', 'Campaign Update'), ('donation_received', 'Donation Received'), ('milestone_reached', 'Milestone Reached'), ('payout_completed', 'Payout Completed'), ('beneficiary_verified', 'Beneficiary Verified'), ('beneficiary_rejected', 'Beneficiary Rejected'), ('general', 'General Notification')], db_index=True, default='general', max_length=50),
        ),
    ]
