# Generated by Django 5.0.14 on 2026-08-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('campaign_update', 'Campaign Update'), ('donation_received', 'Donation Received'), ('milestone_reached', 'Milestone Reached'), ('payout_requested', 'Payout Requested'), ('payout_approved', 'Payout Approved'), ('payout_rejected', 'Payout Rejected'), ('payout_processing', 'Payout Processing'), ('payout_completed', 'Payout Completed'), ('payout_failed', 'Payout Failed'), ('payout_cancelled', 'Payout Cancelled'), ('beneficiary_verified', 'Beneficiary Verified'), ('beneficiary_rejected', 'Beneficiary Rejected'), ('general', 'General Notification')], db_index=True, default='general', max_length=50),
        ),
    ]
