# Generated by Django 5.0.14 on 2026-07-15 00:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('released_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milestones', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['campaign', 'order', 'deadline'],
                'indexes': [models.Index(fields=['campaign', 'status'], name='milestones__campaig_91f2b3_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='milestone',
            constraint=models.CheckConstraint(check=models.Q(('released_amount__lte', models.F('target_amount'))), name='milestone_released_lte_target'),
        ),
        migrations.AddConstraint(
            model_name='milestone',
            constraint=models.CheckConstraint(check=models.Q(('target_amount__gt', 0)), name='milestone_target_gt_0'),
        ),
    ]
