# Generated by Django 5.0.14 on 2026-07-19 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution_partners', '__first__'),
        ('milestones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='execution_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestones', to='execution_partners.executionpartner'),
        ),
    ]
