# Generated by Django 5.0.14 on 2026-07-15 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('documents', '0001_initial'),
        ('milestones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='milestones.milestone'),
        ),
        migrations.AddField(
            model_name='document',
            name='ngo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ngo_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='verification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='campaigns.verification'),
        ),
        migrations.AddField(
            model_name='document',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['campaign'], name='documents_d_campaig_15c53e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['milestone'], name='documents_d_milesto_430353_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['beneficiary'], name='documents_d_benefic_59f0ae_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='documents_d_status_07369e_idx'),
        ),
    ]
