import csv
import io
import json
from abc import ABC, abstractmethod
from decimal import Decimal
from typing import Any, Dict, Iterator, List, Union
from django.utils import timezone
from django.core.exceptions import ValidationError

import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.utils import get_column_letter

from reportlab.lib.pagesizes import letter, landscape
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfgen import canvas

from .constants import REPORT_VERSION, EXPORTER_REGISTRY


def build_report_metadata(user: Any, params: Dict[str, Any], total_records: int) -> Dict[str, Any]:
    """
    Centralized metadata component producing standard audit envelopes across all report formats.
    """
    clean_params = {
        str(k): str(v)
        for k, v in (params or {}).items()
        if k.lower() not in ["format", "page", "page_size", "limit", "offset"]
    }
    user_str = getattr(user, "email", str(user)) if user else "System/Background Worker"
    return {
        "generated_at": timezone.now().isoformat(),
        "generated_by": user_str,
        "filters_applied": clean_params,
        "total_records": total_records,
        "report_version": REPORT_VERSION,
    }


class BaseReportExporter(ABC):
    """
    Abstract base class for all report exporters.
    Encapsulates document rendering exclusively; never instantiates Django HTTP Response objects directly
    so that background Celery workers can invoke generate_content() directly for object storage archival.
    """

    def __init__(
        self,
        data_iterable: Any,
        headers: List[str],
        metadata: Dict[str, Any],
        title: str = "GrantLoop Enterprise Report",
    ):
        self.data_iterable = data_iterable
        self.headers = headers
        self.metadata = metadata
        self.title = title

    @abstractmethod
    def generate_content(self) -> Union[bytes, Iterator[str]]:
        """
        Produces raw byte streams (for binary files like XLSX/PDF) or low-memory line iterators (for CSV).
        """
        pass


class Echo:
    """
    An inline buffer that echoes written strings immediately for StreamingHttpResponse compatibility.
    """
    def write(self, value: str) -> str:
        return value


class CSVExporter(BaseReportExporter):
    """
    Streams CSV format rows efficiently over iterator generators without buffering complete sets in memory.
    """

    def generate_content(self) -> Iterator[str]:
        writer = csv.writer(Echo())

        # Yield structured metadata preamble
        yield writer.writerow(["# GrantLoop Report:", self.title])
        yield writer.writerow(["# Generated At:", self.metadata.get("generated_at", "")])
        yield writer.writerow(["# Generated By:", self.metadata.get("generated_by", "")])
        yield writer.writerow(["# Total Records:", str(self.metadata.get("total_records", 0))])
        yield writer.writerow(["# Report Version:", self.metadata.get("report_version", "")])
        filters = json.dumps(self.metadata.get("filters_applied", {}))
        yield writer.writerow(["# Filters Applied:", filters])
        yield writer.writerow([])  # Empty separator row
        yield writer.writerow(self.headers)

        # Iterate over record stream cleanly
        for row in self.data_iterable:
            if isinstance(row, dict):
                row_vals = [str(row.get(h, "")) if row.get(h) is not None else "" for h in self.headers]
                yield writer.writerow(row_vals)
            elif isinstance(row, (list, tuple)):
                yield writer.writerow([str(v) if v is not None else "" for v in row])
            else:
                yield writer.writerow([str(row)])


class ExcelExporter(BaseReportExporter):
    """
    Generates rich Excel (.xlsx) workbooks featuring frozen headers, bold HSL palettes,
    auto-sized columns, and strict numeric currency/date formatting masks.
    """

    def generate_content(self) -> bytes:
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = "Report Data"

        # Row 1-3: Title and Metadata Summary Header Block
        ws.cell(row=1, column=1, value=self.title).font = Font(bold=True, size=14, color="1E293B")
        meta_sub = f"Generated At: {self.metadata.get('generated_at', '')} | Generated By: {self.metadata.get('generated_by', '')} | Total Records: {self.metadata.get('total_records', 0)} | Version: {self.metadata.get('report_version', '')}"
        ws.cell(row=2, column=1, value=meta_sub).font = Font(italic=True, size=10, color="475569")
        ws.cell(row=3, column=1, value=f"Filters Applied: {json.dumps(self.metadata.get('filters_applied', {}))}").font = Font(italic=True, size=9, color="64748B")

        # Row 5: Frozen, Bold, Slate-Gray Header Row
        header_row_idx = 5
        ws.freeze_panes = f"A{header_row_idx + 1}"
        header_fill = PatternFill("solid", fgColor="2B3A42")
        header_font = Font(bold=True, color="FFFFFF", size=11)

        for col_idx, header in enumerate(self.headers, start=1):
            cell = ws.cell(row=header_row_idx, column=col_idx, value=header)
            cell.fill = header_fill
            cell.font = header_font
            cell.alignment = Alignment(horizontal="center", vertical="center")

        # Rows 6+: Data Row population & native cell format typing
        current_row = header_row_idx + 1
        for row in self.data_iterable:
            for col_idx, header in enumerate(self.headers, start=1):
                val = row.get(header) if isinstance(row, dict) else (row[col_idx - 1] if col_idx - 1 < len(row) else "")
                cell = ws.cell(row=current_row, column=col_idx)

                # Identify financial amounts or decimals for currency formatting
                header_lower = header.lower()
                is_num_col = any(word in header_lower for word in ["amount", "balance", "goal", "raised", "donations", "refunds", "payouts", "revenue"])

                if isinstance(val, Decimal) or (is_num_col and isinstance(val, (int, float, Decimal))):
                    cell.value = float(val)
                    cell.number_format = "#,##0.00"
                    cell.alignment = Alignment(horizontal="right")
                elif "date" in header_lower or "time" in header_lower:
                    cell.value = str(val) if val is not None else ""
                    cell.number_format = "yyyy-mm-dd hh:mm:ss"
                    cell.alignment = Alignment(horizontal="center")
                else:
                    cell.value = str(val) if val is not None else ""
                    if isinstance(val, int) and not is_num_col:
                        cell.value = val

            current_row += 1

        # Auto-size all columns based on content character length
        for col in ws.columns:
            max_len = 0
            col_letter = get_column_letter(col[0].column)
            for cell in col:
                if cell.row >= header_row_idx:
                    val_str = str(cell.value or "")
                    if len(val_str) > max_len:
                        max_len = len(val_str)
            ws.column_dimensions[col_letter].width = max(max_len + 3, 12)

        out = io.BytesIO()
        wb.save(out)
        return out.getvalue()


class NumberedCanvas(canvas.Canvas):
    """
    Two-pass ReportLab canvas recording page count to generate sleek running branding
    headers and 'Page X of Y' footers across all exported document sheets.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_header_footer(num_pages)
            super().showPage()
        super().save()

    def draw_header_footer(self, page_count: int):
        self.saveState()
        # Top Header Branding
        self.setFont("Helvetica-Bold", 8)
        self.setFillColor(colors.HexColor("#64748B"))
        self.drawString(36, self._pagesize[1] - 25, "GRANTLOOP ENTERPRISE REPORTING SYSTEM")
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(36, self._pagesize[1] - 29, self._pagesize[0] - 36, self._pagesize[1] - 29)

        # Bottom Footer Branding & Pagination
        self.setFont("Helvetica", 9)
        self.setFillColor(colors.HexColor("#475569"))
        self.drawString(36, 25, "Confidential & Proprietary – GrantLoop Audit Log")
        self.drawRightString(self._pagesize[0] - 36, 25, f"Page {self._pageNumber} of {page_count}")
        self.restoreState()


class PDFExporter(BaseReportExporter):
    """
    Produces publication-grade ReportLab PDF reports with custom table layouts,
    wrapped cell text, and automatic running headers/footers.
    """

    def generate_content(self) -> bytes:
        out = io.BytesIO()
        # Use landscape orientation to cleanly support 7-9 column grids without truncation
        doc = SimpleDocTemplate(
            out,
            pagesize=landscape(letter),
            leftMargin=36,
            rightMargin=36,
            topMargin=45,
            bottomMargin=45,
        )
        styles = getSampleStyleSheet()
        story = []

        # Document Title and Metadata Paragraphs
        title_style = ParagraphStyle(
            "ReportTitle",
            parent=styles["Title"],
            alignment=0,
            fontSize=16,
            leading=20,
            textColor=colors.HexColor("#1E293B"),
            spaceAfter=6,
        )
        meta_style = ParagraphStyle(
            "ReportMeta",
            parent=styles["Normal"],
            fontSize=9,
            leading=13,
            textColor=colors.HexColor("#475569"),
            spaceAfter=14,
        )
        story.append(Paragraph(f"<b>{self.title}</b>", title_style))
        meta_txt = (
            f"<b>Generated At:</b> {self.metadata.get('generated_at', '')} &nbsp;&nbsp;|&nbsp;&nbsp; "
            f"<b>By:</b> {self.metadata.get('generated_by', '')} &nbsp;&nbsp;|&nbsp;&nbsp; "
            f"<b>Total Records:</b> {self.metadata.get('total_records', 0)}<br/>"
            f"<b>Filters:</b> {json.dumps(self.metadata.get('filters_applied', {}))}"
        )
        story.append(Paragraph(meta_txt, meta_style))

        # Build tabular data structure with wrapped paragraphs to prevent overflow
        cell_style = ParagraphStyle(
            "ReportCell",
            parent=styles["Normal"],
            fontSize=8,
            leading=11,
            textColor=colors.HexColor("#1E293B"),
        )
        header_style = ParagraphStyle(
            "ReportHeaderCell",
            parent=styles["Normal"],
            fontSize=8,
            leading=11,
            textColor=colors.white,
            fontName="Helvetica-Bold",
        )

        table_data = [[Paragraph(h, header_style) for h in self.headers]]
        for row in self.data_iterable:
            row_cells = []
            for h in self.headers:
                val = row.get(h, "") if isinstance(row, dict) else ""
                row_cells.append(Paragraph(str(val) if val is not None else "", cell_style))
            table_data.append(row_cells)

        # Distribute available column widths across the page width (792 - 72 = 720 points)
        available_width = doc.width
        col_width = available_width / max(1, len(self.headers))
        t = Table(table_data, colWidths=[col_width] * len(self.headers), repeatRows=1)
        t.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2B3A42")),
                ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
            ])
        )
        story.append(t)
        doc.build(story, canvasmaker=NumberedCanvas)
        return out.getvalue()


class ZIPExporter(BaseReportExporter):
    """
    Architectural placeholder implementing BaseReportExporter to prepare the system for
    future multi-document archival exports without altering existing service interfaces.
    """

    def generate_content(self) -> bytes:
        raise NotImplementedError("ZIP export is reserved for future multi-document archival.")


def get_exporter(
    format_name: str,
    data_iterable: Any,
    headers: List[str],
    metadata: Dict[str, Any],
    title: str = "GrantLoop Report",
) -> BaseReportExporter:
    """
    Factory function instantiating the appropriate OOP exporter class based on format string.
    """
    fmt_clean = format_name.lower().strip()
    if fmt_clean not in EXPORTER_REGISTRY:
        raise ValueError(f"Unsupported export format '{format_name}'. Must be one of: {', '.join(EXPORTER_REGISTRY.keys())}")

    class_name = EXPORTER_REGISTRY[fmt_clean]
    exporters_map = {
        "CSVExporter": CSVExporter,
        "ExcelExporter": ExcelExporter,
        "PDFExporter": PDFExporter,
        "ZIPExporter": ZIPExporter,
    }
    target_cls = exporters_map.get(class_name)
    if not target_cls:
        raise ValueError(f"Exporter class {class_name} not found in registry map.")

    return target_cls(data_iterable=data_iterable, headers=headers, metadata=metadata, title=title)
