# Generated by Django 5.0.14 on 2026-08-01 06:44

import apps.beneficiaries.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[apps.beneficiaries.validators.validate_date_of_birth]),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='government_id',
            field=models.CharField(max_length=100, unique=True, validators=[apps.beneficiaries.validators.validate_government_id]),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='phone_number',
            field=models.CharField(max_length=30, validators=[apps.beneficiaries.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='beneficiaries/', validators=[apps.beneficiaries.validators.validate_profile_image]),
        ),
        migrations.AddIndex(
            model_name='beneficiary',
            index=models.Index(fields=['verification_status'], name='campaigns_b_verific_1fdaf4_idx'),
        ),
    ]
