# Generated by Django 5.0.14 on 2026-08-01 09:16

import apps.beneficiaries.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0003_sync_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='government_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[apps.beneficiaries.validators.validate_government_id]),
        ),
    ]
