# Generated by Django 5.0.14 on 2026-07-31 13:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('original_currency', models.CharField(max_length=3)),
                ('settled_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('settled_currency', models.CharField(max_length=3)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('gateway_type', models.CharField(max_length=30)),
                ('gateway_order_id', models.CharField(max_length=255, unique=True)),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('receipt_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='campaigns.campaign')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campaign', 'status'], name='donations_d_campaig_5c4298_idx'), models.Index(fields=['donor'], name='donations_d_donor_i_b67ace_idx'), models.Index(fields=['created_at'], name='donations_d_created_26bd74_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='donation',
            constraint=models.CheckConstraint(check=models.Q(('original_amount__gt', 0)), name='donation_original_amount_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='donation',
            constraint=models.CheckConstraint(check=models.Q(('settled_amount__gte', 0)), name='donation_settled_amount_gte_0'),
        ),
    ]
